services:
  - type: web
    name: cyfrowe-search-engine
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ELASTIC_URL
        sync: false
      - key: ELASTIC_API_KEY
        sync: false
      - key: GA4_PROPERTY_ID
        sync: false
      - key: GA4_SERVICE_ACCOUNT_JSON
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.11
